### ISSUE TITLE
ImportError: cannot import name '_worker_manager_loop'

### ISSUE THREAD

**Issue by ABDOELSHEMY** [aamir-mustafa/super-resolution-adversarial-defense#1]
السلام عليكم أخى الكريم أمير
جزاك الله خيراً على مجهودك وعملك الرائع 
عند محاولتى لتجربة المشروع تظهر لى رسالة الخطأ التالية ولم أفلح فى حلها للأسف، أرجو من حضرتك لو كان لديك فكرة عن تجاوز هذا الخطأ أن ترشدنى له
 ولحضرتك خالص الشكر

python main.py --data_test Demo --scale 2 --pre_train download --test_only --save_results
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "G:\Sr\super-resolution-adversarial-defense\src\data\__init__.py", line 2, in <module>
    from dataloader import MSDataLoader
  File "G:\Sr\super-resolution-adversarial-defense\src\dataloader.py", line 17, in <module>
    from torch.utils.data.dataloader import _worker_manager_loop
ImportError: cannot import name '_worker_manager_loop'

**Comment by aamir-mustafa** [comment]
That might be because of the Pytorch version

**Comment by ABDOELSHEMY** [comment]
جزاك الله خيراً أخى لقد قمت بحل المشكلة بالفعل، يمكننى أن أغلق هذه المشكلة بأمان الأن

**Comment by Lane565** [comment]
I have encountered the same problem. How can I solve it？
