### ISSUE TITLE
No such file or directory: 'Labels.mat'

### ISSUE THREAD

**Issue by zhangdong1992** [aamir-mustafa/super-resolution-adversarial-defense#2]
Please upload Corresponding files. Thanks!

**Comment by aamir-mustafa** [comment]
I solved the issue. There is now a sample adversarial image and its corresponding clean image. Accuracy.py can be used to check the model prediction being restored.

**Comment by shudong-zhang** [comment]
thank you very much！I have already solved the problem with my own label
file.

Aamir Mustafa <notifications@github.com>于2019年1月10日 周四18:46写道：
