### ISSUE TITLE
test result

### ISSUE THREAD

**Issue by luyao-cv** [aamir-mustafa/super-resolution-adversarial-defense#5]
I used your test picture img63 (junco) to test. The size of the super-resolution magnification is 598 * 598, and the default of InceptionV3 is 298 * 298, so I changed the target_size to 298 * 298, but the result of the operation It is almost the same as adversarial_images. May I ask why?

**Comment by aamir-mustafa** [comment]
Hi,

That will for sure not work. You need to pass the 2x image through the network. The Inception v3 network can also take 2x images because of the GAP layer in the end.

Thanks
