### ISSUE TITLE
ValueError: Floating point image RGB values must be in the 0..1 range.

### ISSUE THREAD

**Issue by changykang** [aamir-mustafa/super-resolution-adversarial-defense#7]
hello, when i run the Wavelet_Denoising.py file,it is shows the ValueError: Floating point image RGB values must be in the 0..1 range.and when i run the Accuracy.py file, in the recovered images module, it is shows ValueError: Error when checking input: expected input_1 to have shape (299, 299, 3) but got array with shape (598, 598, 3).
So how can i do to solve these problems. thank you

**Comment by amjadnzr** [comment]
@changykang  The Wavelet_Denoising.py file error can be removed by downgrading scikit-image to 0.15.0 version
I am not sure on what you have to do for the Accuracy.py file

**Comment by aamir-mustafa** [comment]
Thanks for raising the issue.

The size of the image should not be an issue for InceptionNet, as it has a global pooling layer at the end of the network. The issue might be with the version of keras.
